language: cpp
sudo: required
dist: trusty
os:
  - linux

services:
  - docker

env:
#  - IMPL=triSYCL CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 TARGET=host
#  - IMPL=triSYCL CXX_COMPILER=clang++-4.0 CC_COMPILER=clang-4.0 TARGET=host

matrix:
  fast_finish: true
# Some tests are not passing on host. We need newer version of computecpp.
#On the current version(0.6.1) of the intel OpenCL some tests are not passing.
  allow_failures:
    - env: IMPL=COMPUTECPP CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 TARGET=opencl
    - env: IMPL=COMPUTECPP CXX_COMPILER=clang++-4.0 CC_COMPILER=clang-4.0 TARGET=opencl
    - env: IMPL=COMPUTECPP CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 TARGET=host
    - env: IMPL=COMPUTECPP CXX_COMPILER=clang++-4.0 CC_COMPILER=clang-4.0 TARGET=host
    - env: IMPL=COMPUTECPP CXX_COMPILER=g++-6 CC_COMPILER=gcc-6 TARGET=opencl
    - env: IMPL=COMPUTECPP CXX_COMPILER=clang++-4.0 CC_COMPILER=clang-4.0 TARGET=opencl


before_install:
  - |
    if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
       export GIT_SLUG=${TRAVIS_REPO_SLUG}
       export GIT_BRANCH=${TRAVIS_BRANCH}
    else
       export GIT_SLUG=${TRAVIS_PULL_REQUEST_SLUG}
       export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
    fi
  - docker build --build-arg c_compiler=${CC_COMPILER}
                 --build-arg cxx_compiler=${CXX_COMPILER}
                 --build-arg git_branch=${GIT_BRANCH}
                 --build-arg git_slug=${GIT_SLUG}
                 --build-arg impl=${IMPL}
                 --build-arg target=${TARGET}
                 -t sycl-blas .

script:
  - docker run sycl-blas
